name: login_authentication
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-417.0.dev <4.0.0'

dependencies:
  firebase_auth: ^4.6.3
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
 
